# Classificador Multiclasse - DATASET IRIS

## Import de dataframe e libs

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

: 

In [2]:
df = pd.read_csv('dados\iris.csv')
df

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
previsores = df.iloc[:, 0:4].values
previsores

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
classes = df.iloc[:, 4].values
classes

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [7]:
previsores_treinamento, previsores_teste, classes_treinamento, classes_teste = train_test_split(previsores, classes, test_size = 0.25)

## Estrutura da Rede Neural

In [14]:
classificador = Sequential()

classificador.add(
    Dense(
        units = 4,
        activation= 'relu',
        input_dim = 4
    )
)
classificador.add(
        Dense(
        units = 4,
        activation= 'relu'
    )
)
classificador.add(
        Dense(
        units = 3,
        activation= 'softmax'
    )
)

In [15]:
classificador.compile(
    optimizer= 'Adam',
    loss = 'categorical_crossentropy',
    metrics = ['categorical_accuracy']
)

### Transformando as classes

In [22]:
labelencoder = LabelEncoder()
classes = labelencoder.fit_transform(classes)
classes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [26]:
classes_dummy = to_categorical(classes)
classes_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [27]:
previsores_treinamento, previsores_teste, classes_treinamento, classes_teste = train_test_split(previsores, classes_dummy, test_size = 0.25)

In [30]:
classificador = Sequential()

classificador.add(
    Dense(
        units = 4,
        activation= 'relu',
        input_dim = 4
    )
)
classificador.add(
        Dense(
        units = 4,
        activation= 'relu'
    )
)
classificador.add(
        Dense(
        units = 3,
        activation= 'softmax'
    )
)

In [31]:
classificador.compile(
    optimizer= 'Adam',
    loss = 'categorical_crossentropy',
    metrics = ['categorical_accuracy']
)

In [32]:
classificador.fit(
    previsores_treinamento, 
    classes_treinamento,
    batch_size= 10,
    epochs= 1000
) 

Epoch 1/1000
12/12 [==============================] - 1s 7ms/step - loss: 1.1586 - categorical_accuracy: 0.3125
Epoch 2/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.1041 - categorical_accuracy: 0.3750
Epoch 3/1000
12/12 [==============================] - 0s 8ms/step - loss: 1.0489 - categorical_accuracy: 0.4375
Epoch 4/1000
12/12 [==============================] - 0s 6ms/step - loss: 1.0262 - categorical_accuracy: 0.5536
Epoch 5/1000
12/12 [==============================] - 0s 11ms/step - loss: 1.0170 - categorical_accuracy: 0.5536
Epoch 6/1000
12/12 [==============================] - 0s 7ms/step - loss: 1.0087 - categorical_accuracy: 0.5446
Epoch 7/1000
12/12 [==============================] - 0s 14ms/step - loss: 0.9981 - categorical_accuracy: 0.5625
Epoch 8/1000
12/12 [==============================] - 0s 7ms/step - loss: 0.9878 - categorical_accuracy: 0.5804
Epoch 9/1000
12/12 [==============================] - 0s 8ms/step - loss: 0.9772 - categorical_accurac

In [33]:
resultado = classificador.evaluate(previsores_teste, classes_teste)

2/2 [==============================] - 0s 3ms/step - loss: 0.1097 - categorical_accuracy: 0.9737


In [34]:
resultado

[0.10974498838186264, 0.9736841917037964]

In [35]:
previsoes = classificador.predict(previsores_teste)

In [37]:
previsoes = (previsoes > 0.5)
previsoes

array([[False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False, False,  True],
       [False, False,  True],
       [Fa

In [40]:
classes_teste2 = [np.argmax(t) for t in classes_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

In [42]:
matriz = confusion_matrix(previsoes2, classes_teste2)
matriz

array([[10,  0,  0],
       [ 0, 14,  0],
       [ 0,  1, 13]], dtype=int64)

## Validação Cruzada

In [46]:
def criar_rede():
    classificador = Sequential()
    classificador.add(
        Dense(
            units = 4,
            activation= 'relu',
            input_dim = 4
        )
    )
    classificador.add(
            Dense(
            units = 4,
            activation= 'relu'
        )
    )
    classificador.add(
            Dense(
            units = 3,
            activation= 'softmax'
        )
    )
    classificador.compile(
        optimizer= 'Adam',
        loss = 'categorical_crossentropy',
        metrics = ['categorical_accuracy']
    )
    return classificador

In [ ]:
classificador = KerasClassifier(
    build_fn = criar_rede,
    epochs = 1000,
    batch_size = 10
)
resultados = cross_val_score(
    estimator = classificador,
    X = previsores,
    y = classes_dummy,
    cv = 10,
    scoring = 'accuracy' 
)

In [49]:
media = resultados.mean()
desvios = resultados.std()
print(media, resultados)

nan [nan nan nan nan nan nan nan nan nan nan]
